[package]
name = "async-test"
version = "0.0.1"
publish = false
edition = "2018"

[dependencies]
futures = "0.3.8"
tokio = { version = "1.0.1", features = ["full"] }

[[example]]
name = "main"
path = "main.rs"

[[example]]
name = "tokio_main"
path = "tokio_main.rs"
