set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/nerdcommenter'

call vundle#end()            " required
filetype plugin indent on    " required


"
" Settings
"

" Not compatible with vi
set nocompatible

" hides buffer instaead of closing them
set hidden

" Syntax on
syntax on

" not working in vim 9.1
" colorscheme delek

autocmd FileType ruby setlocal tabstop=2 shiftwidth=2 softtabstop=2 expandtab
autocmd FileType sh setlocal tabstop=2 shiftwidth=2 softtabstop=2 expandtab
autocmd FileType html setlocal tabstop=2 shiftwidth=2 softtabstop=2 expandtab
autocmd FileType yaml setlocal tabstop=2 shiftwidth=2 softtabstop=2 expandtab
autocmd FileType json setlocal tabstop=2 shiftwidth=2 softtabstop=2 expandtab
autocmd FileType c setlocal tabstop=4 shiftwidth=4 softtabstop=4 expandtab
autocmd FileType python setlocal tabstop=4 shiftwidth=4 softtabstop=4 expandtab
autocmd FileType rust setlocal tabstop=4 shiftwidth=4 softtabstop=4 expandtab
autocmd FileType go setlocal tabstop=4 shiftwidth=4 softtabstop=4
autocmd FileType erlang setlocal tabstop=4 shiftwidth=4 softtabstop=4

" rust filetype
au BufRead,BufNewFile *.rs set filetype=rust

" set python tw as 79
autocmd FileType python setlocal textwidth=79

set hlsearch      " highlight search
set noswapfile    " no swap file
set nobackup      " no backup files

" NERD_COMMENT
let NERDShutUp=1
map <C-h> <leader>c<space>

" Default <leader>='\'
nnoremap <leader>1 yypVr=

" Return to normal when hit jj in insert mode
inoremap jj <ESC>

" inc search
set is

" Set paste mode
set pastetoggle=<F9>

" Re-select region
vmap < <gv
vmap > >gv

" backspace doesn't work on mac and kali
set backspace=indent,eol,start

" fold column
" set foldcolumn=1

" highlight trailing whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" status line
set laststatus=2  " always show status line
set statusline=
set statusline +=%1*\ %n\ %*            "buffer number
set statusline +=%5*%{&ff}%*            "file format
set statusline +=%3*%y%*                "file type
set statusline +=%4*\ %<%F%*            "full path
set statusline +=%2*%m%*                "modified flag
set statusline +=%1*%=%5l%*             "current line
set statusline +=%2*/%L%*               "total lines
set statusline +=%1*%4v\ %*             "virtual column number
set statusline +=%2*0x%04B\ %*          "character under cursor

" Color for status line
hi User1 guifg=#eea040 guibg=#222222 ctermfg=130
hi User2 guifg=#dd3333 guibg=#222222 ctermfg=154
hi User3 guifg=#ff66ff guibg=#222222 ctermfg=124
hi User4 guifg=#a0ee40 guibg=#222222 ctermfg=Green
hi User5 guifg=#eeee40 guibg=#222222 ctermfg=154

" Set to auto read when a file is changed from the outside
set autoread

" tagbar
nnoremap <silent> <F10> :TagbarToggle<CR>
nnoremap <silent> <F8> :NERDTreeToggle<CR>

" Used for gf
set path=.,,include,/usr/local/include,/usr/include

" wrap line
nnoremap qq V}gq
